package com.mazurok.secretFriend.repository.entity;

public enum Stage {
    NO_STAGE,
    CONFIGURE_PROFILE,
    CONFIGURE_FULL_PROFILE,
    CONFIGURE_SECRET_FRIEND_PROFILE,
    CONFIGURE_FULL_SECRET_FRIEND_PROFILE,
    AUTO_LOOKING_FOR_A_FRIEND,
    CHOOSE_FRIEND,
    MESSAGE_REQUEST,
    MESSAGING,
}
